### PR TITLE
Enhancement: remove academy section on home page and tutorial page

### LINKED ISSUE #47: [Enhancement] Remove the academy section
## Motivation / Problem
The academy section is no longer needed on the MVP

## Solution 
- Remove the section from the landing page
- Content can be removed, too

### PR DESCRIPTION
**Pull request by LucaMilanese90**
Fixes #47 

## Proposed Changes

  - remove academy section from home page
  - remove tutorial page
  - remove tutorial modifiers on other component

### CODE REVIEW

**Comment by LucaMilanese90** [comment]
Do we also want to remove all the adaptations made for the tutorial (like all the tutorial booleans passed as props to modify the specific behavior of the various components)?

**Comment by moritzkirstein** [comment]
> Do we also want to remove all the adaptations made for the tutorial (like all the tutorial booleans passed as props to modify the specific behavior of the various components)?

Yes we should revert those changes as well.

**Review by moritzkirstein — APPROVED** [review]
Looks good to me! Thanks for removing the dependencies. I think we should merge this into the mvp branch and start testing the branch early, since especially the tutorial stuff touched a lot of components.

**Comment by LucaMilanese90** [comment]
> Looks good to me! Thanks for removing the dependencies. I think we should merge this into the mvp branch and start testing the branch early, since especially the tutorial stuff touched a lot of components.

I agree, I already tried to publish, buy an asset and start a compute job. Looks like it works but some more tests are not going to hurt.

**Review by oceanByte — APPROVED** [review]

**Pull request merged**
