### PR TITLE
Update site.json

### PR DESCRIPTION
**Pull request by kaimeinke**
Test change of the main menu to include Exchange Logging and Catalogue.

### CODE REVIEW

**Comment by kaimeinke** [comment]
Looking forward to that preview. 😆

**Comment by kaimeinke** [comment]
Okay, I see. This does not work.

**Comment by LucaMilanese90** [comment]
@kaimeinke there is already a preview branch with the new menu style, you can check it out here https://deploy-preview-144--mvg-portal-deltadao.netlify.app/

**Comment by kaimeinke** [comment]
That is awesome @LucaMilanese90 , thank you!

**Pull request closed without merging**
